#!/bin/sh /etc/rc.common
# https://github.com/tlinnet/gas-counter-magnetic/tree/main

START=95
STOP=15

start() {
while true  # Keep an infinite loop to reconnect when connection lost/broker unavailable
do
    now=`date +'%Y-%m-%d %I:%M:%S'`
    echo "START mosquitto_sub listening: ${now}" | tee -a /root/gas_data.log
    mosquitto_sub -h slateplus.lan  -u "gasread" -P "Hello" -v -t "sensors/gas/#" --qos 1 --id "gasread" --disable-clean-session | while read msg
    do
        echo "${msg}" >> /root/gas_data.csv
    done
    sleep 10  # Wait 10 seconds until reconnection
done &  # The last & to run script in background
}

stop() {
    now=`date +'%Y-%m-%d %I:%M:%S'`
    echo "STOP  mosquitto_sub listening: ${now}" | tee -a /root/gas_data.log
    # Find jobs
    pids=`ps | grep 'mosquitto_sub' | grep -v grep | awk '{print $1}'`
    echo "Killing pids: ${pids}" | tee -a /root/gas_data.log
    for pid in $pids; do kill -9 $pid; done
}