#!/bin/sh /etc/rc.common
# https://github.com/tlinnet/gas-counter-magnetic/tree/main

START=95
STOP=15

start() {
echo "/etc/init.d/gas_counter start(): sleeping 10s" | tee -a /root/gas_data.log
sleep 10  # Wait for boot
# Update time: -n Run in foreground, -q Quit after clock is set, -p PEER Obtain time from PEER 
ntpd -n -q -p openwrt.pool.ntp.org | tee -a /root/gas_data.log
now=`date +'%Y-%m-%d %I:%M:%S'`
echo "ntpd updated to: ${now}" | tee -a /root/gas_data.log

while true  # Keep an infinite loop to reconnect when connection lost/broker unavailable
do
    now=`date +'%Y-%m-%d %I:%M:%S'`
    echo "START mosquitto_sub listening: ${now}" | tee -a /root/gas_data.log
    mosquitto_sub -h slateplus.lan  -u "gasread" -P "Hello" -v -t "sensors/gas/#" --qos 1 --id "gasread" --disable-clean-session | while read msg
    do
        echo "${msg}" >> /root/gas_data.csv
    done
    sleep 10  # Wait 10 seconds until reconnection
done &  # The last & to run script in background
}

stop() {
now=`date +'%Y-%m-%d %I:%M:%S'`
echo "/etc/init.d/gas_counter stop(): ${now}" | tee -a /root/gas_data.log

echo "KILL  mosquitto_sub listening: ${now}" | tee -a /root/gas_data.log

# Find jobs: mosquitto_sub
pids=`ps | grep 'mosquitto_sub' | grep -v grep | awk '{print $1}'`
echo "Killing 'mosquitto_sub' pids: ${pids}" | tee -a /root/gas_data.log
for pid in $pids; do kill -9 $pid; done

# Find jobs: boot script
pids=`ps | grep 'gas_counter start' | grep -v grep | awk '{print $1}'`
echo "Killing 'gas_counter start' pids: ${pids}" | tee -a /root/gas_data.log
for pid in $pids; do kill -9 $pid; done
}